__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/bedtools.smk"
include: "rules/bgzip.smk"
include: "rules/imagemagick.smk"
include: "rules/samtools.smk"
include: "rules/tabix.smk"


rule all:
    input:
        unpack(compile_output_list),
