$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  default_container:
    type: string

  samtools_index:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for samtools_index
      container:
        type: string
        description: name or path to docker/singularity container

  bgzip:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bgzip
      container:
        type: string
        description: name or path to docker/singularity container

  required:
    - samples
    - units
    - default_container
